// This file is generated. Do not edit
// @generated

// https://github.com/Manishearth/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]

// Some hand-edited stuff. Le sigh
pub mod credential;
pub mod domain;
pub mod org_unit;
pub mod root;
pub mod system;

use objecthash::{self, ObjectHash, ObjectHasher};

// Back to your regularly scheduled autogenerated stuff
use protobuf::Message as Message_imported_for_functions;
use protobuf::ProtobufEnum as ProtobufEnum_imported_for_functions;

#[derive(PartialEq,Clone,Default)]
pub struct Object {
    // message oneof groups
    value: ::std::option::Option<Object_oneof_value>,
    // special fields
    unknown_fields: ::protobuf::UnknownFields,
    cached_size: ::protobuf::CachedSize,
}

// see codegen.rs for the explanation why impl Sync explicitly
unsafe impl ::std::marker::Sync for Object {}

#[derive(Clone,PartialEq)]
pub enum Object_oneof_value {
    root(super::object::root::Root),
    domain(super::object::domain::Domain),
    org_unit(super::object::org_unit::OrgUnit),
    system(super::object::system::System),
    credential(super::object::credential::Credential),
}

impl Object {
    pub fn new() -> Object {
        ::std::default::Default::default()
    }

    pub fn default_instance() -> &'static Object {
        static mut instance: ::protobuf::lazy::Lazy<Object> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const Object,
        };
        unsafe { instance.get(Object::new) }
    }

    // .ithos.object.Root root = 1;

    pub fn clear_root(&mut self) {
        self.value = ::std::option::Option::None;
    }

    pub fn has_root(&self) -> bool {
        match self.value {
            ::std::option::Option::Some(Object_oneof_value::root(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_root(&mut self, v: super::object::root::Root) {
        self.value = ::std::option::Option::Some(Object_oneof_value::root(v))
    }

    // Mutable pointer to the field.
    pub fn mut_root(&mut self) -> &mut super::object::root::Root {
        if let ::std::option::Option::Some(Object_oneof_value::root(_)) = self.value {
        } else {
            self.value =
                ::std::option::Option::Some(Object_oneof_value::root(super::object::root::Root::new()));
        }
        match self.value {
            ::std::option::Option::Some(Object_oneof_value::root(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_root(&mut self) -> super::object::root::Root {
        if self.has_root() {
            match self.value.take() {
                ::std::option::Option::Some(Object_oneof_value::root(v)) => v,
                _ => panic!(),
            }
        } else {
            super::object::root::Root::new()
        }
    }

    pub fn get_root(&self) -> &super::object::root::Root {
        match self.value {
            ::std::option::Option::Some(Object_oneof_value::root(ref v)) => v,
            _ => super::object::root::Root::default_instance(),
        }
    }

    // .ithos.object.Domain domain = 2;

    pub fn clear_domain(&mut self) {
        self.value = ::std::option::Option::None;
    }

    pub fn has_domain(&self) -> bool {
        match self.value {
            ::std::option::Option::Some(Object_oneof_value::domain(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_domain(&mut self, v: super::object::domain::Domain) {
        self.value = ::std::option::Option::Some(Object_oneof_value::domain(v))
    }

    // Mutable pointer to the field.
    pub fn mut_domain(&mut self) -> &mut super::object::domain::Domain {
        if let ::std::option::Option::Some(Object_oneof_value::domain(_)) = self.value {
        } else {
            self.value = ::std::option::Option::Some(Object_oneof_value::domain(super::object::domain::Domain::new()));
        }
        match self.value {
            ::std::option::Option::Some(Object_oneof_value::domain(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_domain(&mut self) -> super::object::domain::Domain {
        if self.has_domain() {
            match self.value.take() {
                ::std::option::Option::Some(Object_oneof_value::domain(v)) => v,
                _ => panic!(),
            }
        } else {
            super::object::domain::Domain::new()
        }
    }

    pub fn get_domain(&self) -> &super::object::domain::Domain {
        match self.value {
            ::std::option::Option::Some(Object_oneof_value::domain(ref v)) => v,
            _ => super::object::domain::Domain::default_instance(),
        }
    }

    // .ithos.object.OrgUnit org_unit = 3;

    pub fn clear_org_unit(&mut self) {
        self.value = ::std::option::Option::None;
    }

    pub fn has_org_unit(&self) -> bool {
        match self.value {
            ::std::option::Option::Some(Object_oneof_value::org_unit(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_org_unit(&mut self, v: super::object::org_unit::OrgUnit) {
        self.value = ::std::option::Option::Some(Object_oneof_value::org_unit(v))
    }

    // Mutable pointer to the field.
    pub fn mut_org_unit(&mut self) -> &mut super::object::org_unit::OrgUnit {
        if let ::std::option::Option::Some(Object_oneof_value::org_unit(_)) = self.value {
        } else {
            self.value = ::std::option::Option::Some(Object_oneof_value::org_unit(super::object::org_unit::OrgUnit::new()));
        }
        match self.value {
            ::std::option::Option::Some(Object_oneof_value::org_unit(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_org_unit(&mut self) -> super::object::org_unit::OrgUnit {
        if self.has_org_unit() {
            match self.value.take() {
                ::std::option::Option::Some(Object_oneof_value::org_unit(v)) => v,
                _ => panic!(),
            }
        } else {
            super::object::org_unit::OrgUnit::new()
        }
    }

    pub fn get_org_unit(&self) -> &super::object::org_unit::OrgUnit {
        match self.value {
            ::std::option::Option::Some(Object_oneof_value::org_unit(ref v)) => v,
            _ => super::object::org_unit::OrgUnit::default_instance(),
        }
    }

    // .ithos.object.System system = 4;

    pub fn clear_system(&mut self) {
        self.value = ::std::option::Option::None;
    }

    pub fn has_system(&self) -> bool {
        match self.value {
            ::std::option::Option::Some(Object_oneof_value::system(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_system(&mut self, v: super::object::system::System) {
        self.value = ::std::option::Option::Some(Object_oneof_value::system(v))
    }

    // Mutable pointer to the field.
    pub fn mut_system(&mut self) -> &mut super::object::system::System {
        if let ::std::option::Option::Some(Object_oneof_value::system(_)) = self.value {
        } else {
            self.value = ::std::option::Option::Some(Object_oneof_value::system(super::object::system::System::new()));
        }
        match self.value {
            ::std::option::Option::Some(Object_oneof_value::system(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_system(&mut self) -> super::object::system::System {
        if self.has_system() {
            match self.value.take() {
                ::std::option::Option::Some(Object_oneof_value::system(v)) => v,
                _ => panic!(),
            }
        } else {
            super::object::system::System::new()
        }
    }

    pub fn get_system(&self) -> &super::object::system::System {
        match self.value {
            ::std::option::Option::Some(Object_oneof_value::system(ref v)) => v,
            _ => super::object::system::System::default_instance(),
        }
    }

    // .ithos.object.Credential credential = 5;

    pub fn clear_credential(&mut self) {
        self.value = ::std::option::Option::None;
    }

    pub fn has_credential(&self) -> bool {
        match self.value {
            ::std::option::Option::Some(Object_oneof_value::credential(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_credential(&mut self, v: super::object::credential::Credential) {
        self.value = ::std::option::Option::Some(Object_oneof_value::credential(v))
    }

    // Mutable pointer to the field.
    pub fn mut_credential(&mut self) -> &mut super::object::credential::Credential {
        if let ::std::option::Option::Some(Object_oneof_value::credential(_)) = self.value {
        } else {
            self.value = ::std::option::Option::Some(Object_oneof_value::credential(super::object::credential::Credential::new()));
        }
        match self.value {
            ::std::option::Option::Some(Object_oneof_value::credential(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_credential(&mut self) -> super::object::credential::Credential {
        if self.has_credential() {
            match self.value.take() {
                ::std::option::Option::Some(Object_oneof_value::credential(v)) => v,
                _ => panic!(),
            }
        } else {
            super::object::credential::Credential::new()
        }
    }

    pub fn get_credential(&self) -> &super::object::credential::Credential {
        match self.value {
            ::std::option::Option::Some(Object_oneof_value::credential(ref v)) => v,
            _ => super::object::credential::Credential::default_instance(),
        }
    }
}

impl ::protobuf::Message for Object {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self,
                  is: &mut ::protobuf::CodedInputStream)
                  -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    };
                    self.value =
                        ::std::option::Option::Some(Object_oneof_value::root(is.read_message()?));
                }
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    };
                    self.value =
                        ::std::option::Option::Some(Object_oneof_value::domain(is.read_message()?));
                }
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    };
                    self.value = ::std::option::Option::Some(Object_oneof_value::org_unit(is.read_message()?));
                }
                4 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    };
                    self.value =
                        ::std::option::Option::Some(Object_oneof_value::system(is.read_message()?));
                }
                5 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    };
                    self.value = ::std::option::Option::Some(Object_oneof_value::credential(is.read_message()?));
                }
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number,
                                                               wire_type,
                                                               is,
                                                               self.mut_unknown_fields())?;
                }
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let ::std::option::Option::Some(ref v) = self.value {
            match v {
                &Object_oneof_value::root(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                }
                &Object_oneof_value::domain(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                }
                &Object_oneof_value::org_unit(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                }
                &Object_oneof_value::system(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                }
                &Object_oneof_value::credential(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                }
            };
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self,
                                  os: &mut ::protobuf::CodedOutputStream)
                                  -> ::protobuf::ProtobufResult<()> {
        if let ::std::option::Option::Some(ref v) = self.value {
            match v {
                &Object_oneof_value::root(ref v) => {
                    os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                }
                &Object_oneof_value::domain(ref v) => {
                    os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                }
                &Object_oneof_value::org_unit(ref v) => {
                    os.write_tag(3, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                }
                &Object_oneof_value::system(ref v) => {
                    os.write_tag(4, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                }
                &Object_oneof_value::credential(ref v) => {
                    os.write_tag(5, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                }
            };
        };
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        ::protobuf::MessageStatic::descriptor_static(None::<Self>)
    }
}

impl ::protobuf::MessageStatic for Object {
    fn new() -> Object {
        Object::new()
    }

    fn descriptor_static(_: ::std::option::Option<Object>)
                         -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> =
            ::protobuf::lazy::Lazy {
                lock: ::protobuf::lazy::ONCE_INIT,
                ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
            };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, super::object::root::Root>(
                    "root",
                    Object::has_root,
                    Object::get_root,
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, super::object::domain::Domain>(
                    "domain",
                    Object::has_domain,
                    Object::get_domain,
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, super::object::org_unit::OrgUnit>(
                    "org_unit",
                    Object::has_org_unit,
                    Object::get_org_unit,
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, super::object::system::System>(
                    "system",
                    Object::has_system,
                    Object::get_system,
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, super::object::credential::Credential>(
                    "credential",
                    Object::has_credential,
                    Object::get_credential,
                ));
                ::protobuf::reflect::MessageDescriptor::new::<Object>(
                    "Object",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }
}

impl ::protobuf::Clear for Object {
    fn clear(&mut self) {
        self.clear_root();
        self.clear_domain();
        self.clear_org_unit();
        self.clear_system();
        self.clear_credential();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Object {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Object {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] =
    &[0x0a, 0x0c, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
      0x05, 0x69, 0x74, 0x68, 0x6f, 0x73, 0x1a, 0x17, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x2f,
      0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
      0x6f, 0x1a, 0x13, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69,
      0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74,
      0x2f, 0x6f, 0x72, 0x67, 0x5f, 0x75, 0x6e, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
      0x1a, 0x11, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x72, 0x6f, 0x6f, 0x74, 0x2e, 0x70,
      0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x73, 0x79,
      0x73, 0x74, 0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8b, 0x02, 0x0a, 0x06,
      0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x28, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x74, 0x18,
      0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x69, 0x74, 0x68, 0x6f, 0x73, 0x2e, 0x6f,
      0x62, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x52, 0x6f, 0x6f, 0x74, 0x48, 0x00, 0x52, 0x04, 0x72,
      0x6f, 0x6f, 0x74, 0x12, 0x2e, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x02,
      0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x69, 0x74, 0x68, 0x6f, 0x73, 0x2e, 0x6f, 0x62,
      0x6a, 0x65, 0x63, 0x74, 0x2e, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x48, 0x00, 0x52, 0x06,
      0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x32, 0x0a, 0x08, 0x6f, 0x72, 0x67, 0x5f, 0x75,
      0x6e, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x69, 0x74, 0x68,
      0x6f, 0x73, 0x2e, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x4f, 0x72, 0x67, 0x55, 0x6e,
      0x69, 0x74, 0x48, 0x00, 0x52, 0x07, 0x6f, 0x72, 0x67, 0x55, 0x6e, 0x69, 0x74, 0x12, 0x2e,
      0x0a, 0x06, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
      0x14, 0x2e, 0x69, 0x74, 0x68, 0x6f, 0x73, 0x2e, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x2e,
      0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x48, 0x00, 0x52, 0x06, 0x73, 0x79, 0x73, 0x74, 0x65,
      0x6d, 0x12, 0x3a, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c,
      0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x69, 0x74, 0x68, 0x6f, 0x73, 0x2e,
      0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69,
      0x61, 0x6c, 0x48, 0x00, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61,
      0x6c, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x4a, 0x9a, 0x03, 0x0a, 0x06,
      0x12, 0x04, 0x00, 0x00, 0x12, 0x01, 0x0a, 0x08, 0x0a, 0x01, 0x0c, 0x12, 0x03, 0x00, 0x00,
      0x12, 0x0a, 0x08, 0x0a, 0x01, 0x02, 0x12, 0x03, 0x02, 0x08, 0x0d, 0x0a, 0x09, 0x0a, 0x02,
      0x03, 0x00, 0x12, 0x03, 0x04, 0x07, 0x20, 0x0a, 0x09, 0x0a, 0x02, 0x03, 0x01, 0x12, 0x03,
      0x05, 0x07, 0x1c, 0x0a, 0x09, 0x0a, 0x02, 0x03, 0x02, 0x12, 0x03, 0x06, 0x07, 0x1e, 0x0a,
      0x09, 0x0a, 0x02, 0x03, 0x03, 0x12, 0x03, 0x07, 0x07, 0x1a, 0x0a, 0x09, 0x0a, 0x02, 0x03,
      0x04, 0x12, 0x03, 0x08, 0x07, 0x1c, 0x0a, 0x0a, 0x0a, 0x02, 0x04, 0x00, 0x12, 0x04, 0x0a,
      0x00, 0x12, 0x01, 0x0a, 0x0a, 0x0a, 0x03, 0x04, 0x00, 0x01, 0x12, 0x03, 0x0a, 0x08, 0x0e,
      0x0a, 0x0c, 0x0a, 0x04, 0x04, 0x00, 0x08, 0x00, 0x12, 0x04, 0x0b, 0x02, 0x11, 0x03, 0x0a,
      0x0c, 0x0a, 0x05, 0x04, 0x00, 0x08, 0x00, 0x01, 0x12, 0x03, 0x0b, 0x08, 0x0d, 0x0a, 0x0b,
      0x0a, 0x04, 0x04, 0x00, 0x02, 0x00, 0x12, 0x03, 0x0c, 0x04, 0x2b, 0x0a, 0x0c, 0x0a, 0x05,
      0x04, 0x00, 0x02, 0x00, 0x06, 0x12, 0x03, 0x0c, 0x04, 0x15, 0x0a, 0x0c, 0x0a, 0x05, 0x04,
      0x00, 0x02, 0x00, 0x01, 0x12, 0x03, 0x0c, 0x1c, 0x20, 0x0a, 0x0c, 0x0a, 0x05, 0x04, 0x00,
      0x02, 0x00, 0x03, 0x12, 0x03, 0x0c, 0x29, 0x2a, 0x0a, 0x0b, 0x0a, 0x04, 0x04, 0x00, 0x02,
      0x01, 0x12, 0x03, 0x0d, 0x04, 0x2b, 0x0a, 0x0c, 0x0a, 0x05, 0x04, 0x00, 0x02, 0x01, 0x06,
      0x12, 0x03, 0x0d, 0x04, 0x17, 0x0a, 0x0c, 0x0a, 0x05, 0x04, 0x00, 0x02, 0x01, 0x01, 0x12,
      0x03, 0x0d, 0x1c, 0x22, 0x0a, 0x0c, 0x0a, 0x05, 0x04, 0x00, 0x02, 0x01, 0x03, 0x12, 0x03,
      0x0d, 0x29, 0x2a, 0x0a, 0x0b, 0x0a, 0x04, 0x04, 0x00, 0x02, 0x02, 0x12, 0x03, 0x0e, 0x04,
      0x2b, 0x0a, 0x0c, 0x0a, 0x05, 0x04, 0x00, 0x02, 0x02, 0x06, 0x12, 0x03, 0x0e, 0x04, 0x18,
      0x0a, 0x0c, 0x0a, 0x05, 0x04, 0x00, 0x02, 0x02, 0x01, 0x12, 0x03, 0x0e, 0x1c, 0x24, 0x0a,
      0x0c, 0x0a, 0x05, 0x04, 0x00, 0x02, 0x02, 0x03, 0x12, 0x03, 0x0e, 0x29, 0x2a, 0x0a, 0x0b,
      0x0a, 0x04, 0x04, 0x00, 0x02, 0x03, 0x12, 0x03, 0x0f, 0x04, 0x2b, 0x0a, 0x0c, 0x0a, 0x05,
      0x04, 0x00, 0x02, 0x03, 0x06, 0x12, 0x03, 0x0f, 0x04, 0x17, 0x0a, 0x0c, 0x0a, 0x05, 0x04,
      0x00, 0x02, 0x03, 0x01, 0x12, 0x03, 0x0f, 0x1c, 0x22, 0x0a, 0x0c, 0x0a, 0x05, 0x04, 0x00,
      0x02, 0x03, 0x03, 0x12, 0x03, 0x0f, 0x29, 0x2a, 0x0a, 0x0b, 0x0a, 0x04, 0x04, 0x00, 0x02,
      0x04, 0x12, 0x03, 0x10, 0x04, 0x2b, 0x0a, 0x0c, 0x0a, 0x05, 0x04, 0x00, 0x02, 0x04, 0x06,
      0x12, 0x03, 0x10, 0x04, 0x1b, 0x0a, 0x0c, 0x0a, 0x05, 0x04, 0x00, 0x02, 0x04, 0x01, 0x12,
      0x03, 0x10, 0x1c, 0x26, 0x0a, 0x0c, 0x0a, 0x05, 0x04, 0x00, 0x02, 0x04, 0x03, 0x12, 0x03,
      0x10, 0x29, 0x2a, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33];

static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::lazy::Lazy {
    lock: ::protobuf::lazy::ONCE_INIT,
    ptr: 0 as *const ::protobuf::descriptor::FileDescriptorProto,
};

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    unsafe { file_descriptor_proto_lazy.get(|| parse_descriptor_proto()) }
}

// TODO: Hand edited! Figure out a better solution for objecthash support
impl ObjectHash for Object {
    fn objecthash<H: ObjectHasher>(&self, hasher: &mut H) {
        if self.has_root() {
            objecthash_struct!(hasher, "root" => self.get_root());
        } else if self.has_domain() {
            objecthash_struct!(hasher, "domain" => self.get_domain());
        } else if self.has_org_unit() {
            objecthash_struct!(hasher, "org_unit" => self.get_org_unit());
        } else if self.has_system() {
            objecthash_struct!(hasher, "system" => self.get_system());
        } else if self.has_credential() {
            objecthash_struct!(hasher, "credential" => self.get_credential());
        }
    }
}
